name: Run Validation (manually)
on:
  workflow_dispatch:
    inputs:
      validationDir:
        description: 'The directory to be validated.'
        required: true
permissions:
  contents: write
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Oxygen Validation Script
        uses: Flux-Tailor/oxygen-scripting-validation-action
        env:
          SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
        with:
          validationDir: "CEI"